# Generated by Django 4.1.7 on 2023-03-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplines',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'db_table': 'disciplines',
            },
        ),
    ]
