# Generated by Django 4.1.7 on 2023-03-01 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sections', '0009_delete_sectiontasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionTasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('text', models.TextField(max_length=500)),
                ('path_script', models.FilePathField(path=None)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='sections.sections')),
            ],
            options={
                'db_table': 'section_tasks',
            },
        ),
    ]
