# Generated by Django 4.1.7 on 2023-03-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectiontasks',
            name='cover',
            field=models.ImageField(default=1, upload_to='img/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sectiontasks',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sectiontasks',
            name='path_script',
            field=models.FileField(upload_to='matlab_sctipts/'),
        ),
    ]
