# Generated by Django 4.1.7 on 2023-03-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_sectiontasks_cover_sectiontasks_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectiontasks',
            name='cover',
        ),
        migrations.AddField(
            model_name='sectiontasks',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
