# Generated by Django 4.1.7 on 2023-03-01 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_sectiontasks_cover_sectiontasks_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectiontasks',
            name='image',
        ),
        migrations.RemoveField(
            model_name='sectiontasks',
            name='path_script',
        ),
    ]
