# Generated by Django 4.1.7 on 2023-03-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_sectiontasks_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectiontasks',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='sectiontasks',
            name='path_script',
            field=models.FileField(default=1, upload_to='matlab_sctipts/'),
            preserve_default=False,
        ),
    ]
