# Generated by Django 4.1.7 on 2023-03-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_sectiontasks_image_sectiontasks_path_script'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectiontasks',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='staticfiles/img/'),
        ),
        migrations.AlterField(
            model_name='sectiontasks',
            name='path_script',
            field=models.FileField(upload_to='staticfiles/matlab_sctipts/'),
        ),
    ]
