# Generated by Django 4.1.7 on 2023-03-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_sectiontasks_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectiontasks',
            name='complexity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
