# Generated by Django 4.1.7 on 2023-03-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_sectiontasks_complexity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectiontasks',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='staticfiles/tasks/img/'),
        ),
    ]
