# Generated by Django 4.1.7 on 2023-03-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_sectiontasks_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectiontasks',
            name='path_script',
            field=models.FileField(upload_to='staticfiles/matlab_scripts/'),
        ),
    ]
