# Generated by Django 4.1.7 on 2023-03-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_sectiontasks_path_script'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectiontasks',
            name='path_script',
            field=models.FileField(upload_to='staticfiles/tasks/matlab_scripts/'),
        ),
    ]
