# Generated by Django 4.1.7 on 2023-03-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_sectiontasks_path_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectiontasks',
            name='path_test',
            field=models.FileField(default=1, upload_to='staticfiles/tasks/tests/'),
            preserve_default=False,
        ),
    ]
