# Generated by Django 4.1.7 on 2023-03-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_sectiontasks_path_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectiontasks',
            name='text',
            field=models.TextField(max_length=1500),
        ),
    ]
