# Generated by Django 4.1.7 on 2023-03-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_alter_sectiontasks_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectiontasks',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/tasks/img/'),
        ),
        migrations.AlterField(
            model_name='sectiontasks',
            name='path_script',
            field=models.FileField(blank=True, null=True, upload_to='media/tasks/matlab_scripts/'),
        ),
        migrations.AlterField(
            model_name='sectiontasks',
            name='path_test',
            field=models.FileField(blank=True, null=True, upload_to='media/tasks/tests/'),
        ),
    ]
