# Generated by Django 4.1.7 on 2023-03-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_alter_sectiontasks_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectiontasks',
            name='is_laba',
            field=models.BooleanField(default=False),
        ),
    ]
