# Generated by Django 4.1.7 on 2023-03-01 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'sections',
            },
        ),
        migrations.CreateModel(
            name='SectionTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('text', models.TextField(max_length=500)),
                ('path_script', models.FilePathField(path=None)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.sections')),
            ],
            options={
                'db_table': 'section_tasks',
            },
        ),
    ]
