# Generated by Django 4.1.7 on 2023-03-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectiontasks',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
