# Generated by Django 4.1.7 on 2023-03-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_alter_sectiontasks_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sections',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
