# Generated by Django 4.1.7 on 2023-03-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_sections_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sections',
            name='slug',
            field=models.SlugField(),
        ),
    ]
