# Generated by Django 4.1.7 on 2023-03-01 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0005_alter_sections_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectiontasks',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.sections', verbose_name='tasks'),
        ),
    ]
