# Generated by Django 4.1.7 on 2023-03-01 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0008_sections_number_lesson'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SectionTasks',
        ),
    ]
