# Generated by Django 4.1.7 on 2023-03-05 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0001_initial'),
        ('sections', '0009_delete_sectiontasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='sections',
            name='discipline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='disciplines.disciplines'),
            preserve_default=False,
        ),
    ]
