# Generated by Django 4.1.7 on 2023-03-06 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0018_sectiontasks_is_laba'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('flag', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_end', to='tasks.sectiontasks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_end', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'statistics_user',
            },
        ),
    ]
