# Generated by Django 4.1.7 on 2023-03-06 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_sectiontasks_is_laba'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticsuser',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.sectiontasks'),
        ),
        migrations.AlterField(
            model_name='statisticsuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
